### ISSUE TITLE
Add second webhead

### ISSUE THREAD

**Issue by barryclark** [DoSomething/voting-app#218]
Plan here: https://gist.github.com/mshmsh5000/e465931be8f69008ed78

This is fourth in priority behind ensuring monitoring is in place, using Redis for cache and session storage, and moving MySQL to a dedicated machine.

The priority is lower because the complexity is higher, and we should get some better scalability bang for the buck by making the other changes first.

**Comment by DFurnes** [comment]
I'm thinking this is probably safe to close. @mshmsh5000?

**Comment by mshmsh5000** [comment]
+1
