### ISSUE TITLE
Move MySQL to dedicated server

### ISSUE THREAD

**Issue by barryclark** [DoSomething/voting-app#219]
Plan here: https://gist.github.com/mshmsh5000/e465931be8f69008ed78

This is third in priority behind ensuring monitoring is in place and using Redis for cache and session storage.

**Comment by DFurnes** [comment]
Likewise, I'm thinking this is probably safe to close now. @mshmsh5000?

**Comment by mshmsh5000** [comment]
Sure. We can reopen if scalability becomes a concern.
