### ISSUE TITLE
Mobile collection for international

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#281]
Optionally, allow for international users to add their cell number

**Comment by DFurnes** [comment]
So, the plan is: 
- For **domestic** users, phone is required & hide email field
- For **international** users, email is required & hide phone field
- For some countries, we'll _also_ show an optional phone field. For example, we might only collect phone numbers in UK and Brazil.

:telephone_receiver:

**Comment by angaither** [comment]
:mobile_phone_off: :email:
