### ISSUE TITLE
Closed state name collection

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#286]
When the app is closed, have a form to INFORM me more. 
aka, alway be collecting (user info)

-------

__Update:__ Things to do –

 * [x] Add `show_candidates` setting to show or hide candidate listing.
 * [x] Add endpoint for closed state form.
 * [x] Put users into a transactional bucket when they submit the closed state form.

:computer:

**Comment by DFurnes** [comment]
~~Two~~ three questions –
1. Should this _just_ collect email addresses, or have the same logic of collecting email/phone/both based on country (like the voting form)?
2. Should users be created in Voting App & Northstar from the closed state form?
3. I assume that these users will be forwarded through Message Broker into a certain bucket either way. Is that set up yet?

**Comment by angaither** [comment]
1. Probably, the second choice. 
2. YES!
3. We could probably save it as `source:agg_closed` or something

**Comment by DFurnes** [comment]
Things to do –

 * [ ] Add `show_candidates` setting to show or hide candidate listing.
 * [ ] Add `closed_state` setting to show or hide closed state form.
 * [ ] Add endpoint for closed state form.

:computer:

**Comment by DFurnes** [comment]
I added the form in #324, which will appear on the bottom of the page whenever voting is disabled. We still need to figure out what queue (on Message Broker) this should be sent to for users to be placed in the proper messaging buckets.

/cc @DeeZone

**Comment by deezone** [comment]
@DFurnes I think the plan for the "closed state" is to change the message payload from:

```
...
'application_id' => 'AGG",
'activity' => 'vote'
...
```

to

```
...
'application_id' => 'AGG",
'activity' => 'closed'
...
```

**Comment by joolaay** [comment]
@DFurnes @angaither hey guys - who's assigned to this guy?

**Comment by DFurnes** [comment]
Keeping this as lower priority, since we won't need it for launch. Either one of us could take it on as time becomes available.
