### ISSUE TITLE
Candidates have tags 

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#291]
like country of origin, country they play for, team

**Comment by DFurnes** [comment]
It sounds like the only tag that we'll actually be using is the category name (e.g. type of sport). We might be able to get away without building a tagging interface then... Will check with Naomi.

**Comment by DFurnes** [comment]
Either way, we'll need to add a hook to forward that tag or category name to Northstar under the `interests` field. (References #322)

**Comment by DFurnes** [comment]
Interests are now being tagged in Northstar as of #323.

**Comment by DFurnes** [comment]
Closing this, since we're no longer building this functionality.
