### ISSUE TITLE
Missing Fastly country code header

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#333]
Requests sent to Message Broker are missing the `country_code` value:

```
s:12:"country_code";s:0:""
```

**Comment by DFurnes** [comment]
It looks like the Fastly headers aren't being set. Any ideas @blisteringherb?

**Comment by DFurnes** [comment]
This is from testing on [www.catsgonegood.com](http://www.catsgonegood.com) btw.

**Comment by DFurnes** [comment]
For reference, expected functionality can be tested by using `?country_code=` query string to override country code for the current session. For example visiting [`www.catsgonegood.com/?country_code=GB`](http://www.catsgonegood.com/?country_code=GB) will simulate being in the motherland for the remainder of that browsing session. :gb:

**Comment by blisteringherb** [comment]
Nginx was attempting and failing to set the header, but because it's not receiving the real IP from the end user, it was just overwriting the actual country code that Fastly was passing through. I removed setting that country code in Nginx, and Fastly is passing the header through properly now.

**Comment by DFurnes** [comment]
F'yeah! Verified to be working now on Cats Gone Good! :hammer:
