### ISSUE TITLE
No SMS Notification Received on US Site

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#352]
After user votes and enters valid phone number, no SMS is received acknowledging the vote.

No text received on at least Firefox and Chrome.

**Comment by DFurnes** [comment]
@DeeZone Any ideas?

**Comment by deezone** [comment]
@namimody What was the phone number in the test?

**Comment by namimody** [comment]
860 989 0489!

On Fri, Jun 19, 2015 at 1:31 PM, DeeZone notifications@github.com wrote:

> @namimody https://github.com/namimody What was the phone number in the
> test?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/voting-app/issues/352#issuecomment-113582650
> .

## 

Namita (Nami) Mody

Junior Product Manager
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255

**Comment by deezone** [comment]
Tested with supplied phone number - Mobile Commons confirms:
- campaign signup
- SMS message sent
- tags set:
  - AGG2015_1st_vote  
  - AGG2015_1st_vote_gender 
  - AGG2015_1st_vote_id

**Comment by DFurnes** [comment]
@namimody The SMS message is only triggered on the user's first vote, so if you test multiple times with the same number you won't receive duplicate messages.

**Comment by mikefantini** [comment]
@namimody are you good to close this one out?
