### ISSUE TITLE
Email notification confirming vote not received after more than 5 minutes on GB site

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#354]
On the GB site, user enters valid email when voting, but no notification is received. All browsers and devices are affected.

**Comment by deezone** [comment]
@namimody I think this issue has been resolved?

**Comment by namimody** [comment]
@DeeZone I just tried on nmody@dosomething.org on catsgonegood.com and got a test SMS!

Tried nmody+cggtest6@dosomething.org on GB site and got a transactional email. Woot.

(^amended)

**Comment by DFurnes** [comment]
Awesome, closing! :hammer:
