### ISSUE TITLE
No Error for Incorrect Cell # Format

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#358]
Entering "1" into the cell number field makes all the content (form, cats, etc.) disappear and no error message is produced.

Firefox 33/OS X Yosemite

![image](https://cloud.githubusercontent.com/assets/12396076/8257143/95a6776c-1679-11e5-82e2-5372edc6f756.png)

**Comment by DFurnes** [comment]
This should be fixed by #357.
