### ISSUE TITLE
Clicking "Vote" Does Not Center Voting Form in Window

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#359]
When you click vote, sometimes the form appears but below the fold, so the user doesn't know that anything has happened. Sometimes, clicking vote opens the accordion but in a way that is not centered (see image).

At least Chrome 43 + Firefox 36 on OS X Yosemite, likely across browsers.

![image](https://cloud.githubusercontent.com/assets/12396076/8257230/20cb3dc8-167a-11e5-8b59-67e6c5e25db1.png)

**Comment by namimody** [comment]
@DFurnes this doesn't seem to be working on Firefox -- any ideas?
![image](https://cloud.githubusercontent.com/assets/12396076/8364646/c1d57c30-1b55-11e5-9c21-f8a0a5a6b81c.png)

**Comment by DFurnes** [comment]
@namimody I'm having trouble reproducing any issues on Firefox 38.0.5. Is it not scrolling to the selected row? If not, can you press `Alt-Command-I` and paste a screenshot of anything that appears in the Console tab?

**Comment by DFurnes** [comment]
Can you also post what version of Firefox you're seeing issues on?

**Comment by namimody** [comment]
After chatting with @DFurnes, seems like this is more a function of the size of the window -- never mind!
