### ISSUE TITLE
Incorrect Cell Input Results in Error, but not near Field

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#361]
Unsure if this is expected behavior, but on Safari and Chrome the cell phone error message appears as a bullet at the top of the form rather by the cell field.

![image](https://cloud.githubusercontent.com/assets/12396076/8257774/12e0898a-167e-11e5-8d78-26bc4f4cd211.png)

**Comment by DFurnes** [comment]
This is expected behavior, although we should add some nicer styling for that component.
