### ISSUE TITLE
Submitting Another Vote w/ Same Number Results in Unskinned Error

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#362]
I'm 90% sure I submitted a vote with my cell (860 989 0489, but I can't guarantee because transactionals aren't working) and then if I tried to reenter that number, it results in the image below.

Chrome 41

![image](https://cloud.githubusercontent.com/assets/12396076/8257875/a83f470a-167e-11e5-8e0a-99cd7bd69092.png)

**Comment by DFurnes** [comment]
Ahh, yeah that's a bug. :bug: 

From server logs:
![screen shot 2015-06-19 at 12 59 04 pm](https://cloud.githubusercontent.com/assets/583202/8258459/06e9c9d4-1683-11e5-8c48-6856022897f4.png)

**Comment by DFurnes** [comment]
I think the issue is that we're checking that phone value is unique, but _not_ running the setter (which removes spaces, dashes, etc.) before doing so. So it sees that `(555) 555-5555` isn't in the database, but then hits a constraint violation when it tries to enter `5555555555`.
