### ISSUE TITLE
Did not Receive Email Transactional After SIgning Up on ES or GB Site

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#366]
Signed up with nmody@dosomething.org

**Comment by deezone** [comment]
@DFurnes Can you provide some details on what defines "ES" or "GB" site? Perhaps a URL so I can test?

**Comment by DFurnes** [comment]
@DeeZone [`http://www.catsgonegood.com/?country_code=ES`](http://www.catsgonegood.com/?country_code=ES) and [`http://www.catsgonegood.com/?country_code=GB`](http://www.catsgonegood.com/?country_code=GB)

**Comment by deezone** [comment]
@DFurnes @namimody The email transactionals for these countries as been tested to be working. Nami should have the related email messages in the related inbox.

**Comment by namimody** [comment]
Got 3, Dee! Woot. Is there any way to tell which countries they are for or
are they all the same?

On Sun, Jun 21, 2015 at 11:54 PM, DeeZone notifications@github.com wrote:

> @DFurnes https://github.com/DFurnes @namimody
> https://github.com/namimody The email transactionals for these
> countries as been tested to be working. Nami should have the related email
> messages in the related inbox.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoSomething/voting-app/issues/366#issuecomment-113995418
> .

## 

Namita (Nami) Mody

Junior Product Manager
@dosomething http://twitter.com/dosomething @imanami13
https://twitter.com/imanami13
(212) 254-2390 x255

**Comment by deezone** [comment]
All the same, regardless of the country with the exception of "US" which
produces a SMS message.

**Comment by DFurnes** [comment]
Is this safe to close now? Seems to be working for me as well. :+1:

**Comment by mikefantini** [comment]
@DeeZone any idea why there was such a delay in @namimody receiving the emails?

@namimody it took about 2 days for you to get emails correct?

**Comment by DFurnes** [comment]
I'm not seeing any delay on messaging. Can you verify that you're still seeing delays as an issue @namimody @mikefantini?

**Comment by mikefantini** [comment]
@DFurnes i didn't test, just seemed like there was a delay. if you can test and verify that there isn't a delay then please close!

**Comment by DFurnes** [comment]
I tested a few times, and got messages instantly. Please re-open if issues resurface. :)
