### ISSUE TITLE
No Image on Facebook Share

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#367]
![image](https://cloud.githubusercontent.com/assets/12396076/8258403/9aedb9b6-1682-11e5-89d9-42e12913cd23.png)

**Comment by DFurnes** [comment]
Fixed!

![screen shot 2015-06-22 at 4 56 07 pm](https://cloud.githubusercontent.com/assets/583202/8292817/9d237354-18ff-11e5-9fd1-95ab7b46fa87.png)

**Comment by DFurnes** [comment]
Share image can be overridden from the settings admin panel (for site-specific branding).
