### ISSUE TITLE
When Clicking Vote then Searching, Form Persists in Filter View

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#368]
Addtional search results follow after form.

![image](https://cloud.githubusercontent.com/assets/12396076/8258518/87153422-1683-11e5-8ae8-a1aef6ef97c2.png)

**Comment by DFurnes** [comment]
The form will stay open and "attached" to whatever candidate you were viewing before typing into the search field. This is expected behavior, but something we can change if we think it's confusing from a UX perspective.

@mikefantini Thoughts?

**Comment by joolaay** [comment]
@DFurnes s it open during search both pre-vote and post-vote?

**Comment by DFurnes** [comment]
@julielorch You can play around with the current behavior on [www.catsgonegood.com](http://www.catsgonegood.com). The drawer functions exactly the same regardless of whether the user has voted or not.

**Comment by joolaay** [comment]
@DFurnes I don't think that's confusing. It's also unlikely that a user will search for a cat that's already found, or if they are searching for a new cat, that the new cat has some of the same search terms as the alpha cat. AKA this is not a mission critical fix from a UX perspective, either would be okay.

**Comment by DFurnes** [comment]
Ok, closing! :hammer:
