### ISSUE TITLE
Start or restart React rendering process during deploys

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#372]
Capistrano deploy script should run `forever stopall && forever start bootstrap/react_server.js`.

References #347.

**Comment by blisteringherb** [comment]
@DFurnes  Any preference on when this task should be run?  Is it fine to run after the artisan cache:clear?

**Comment by DFurnes** [comment]
Might be good to run right before that, in case we decide to cache the rendered views.

**Comment by DFurnes** [comment]
This was done in #388! :clap:
