### ISSUE TITLE
Transactional emails not sending

### ISSUE THREAD

**Issue by marahml** [DoSomething/voting-app#379]
Signed up / voted in AGG (cats gone good) at 4:50 on June 23 and have not received a transactional email

**Comment by sergiitk** [comment]
Just did the same, works for me:
![image](https://cloud.githubusercontent.com/assets/672669/8317389/cd370892-1a05-11e5-94b4-0efac359b994.png)

**Comment by sergiitk** [comment]
Went through queue:

```
------- mbc-transactional-email - consumeTransactionalQueue() START -------
-> mbc-transactional-email Mandrill message sent: sergii+test-062415-12@dosomething.org - Tue Jun 23 17:10:53 EDT 2015
```

**Comment by DFurnes** [comment]
Same, just got a transactional message a few seconds after signing up.
