### ISSUE TITLE
Incorrect transactional triggering

### ISSUE THREAD

**Issue by marahml** [DoSomething/voting-app#380]
Currently transactional email being triggered (received by Micah, Marah has still not received an email) is old template: https://mandrillapp.com/templates/code?id=agg2015-voting-confirmation-global-non-affiliates

Correct transactional email is: https://mandrillapp.com/templates/code?id=agg2015-voting-confirmation-global

**Comment by mshmsh5000** [comment]
This is an [env var](https://github.com/DoSomething/voting-app/blob/dev/app/Handlers/Events/SendFirstVoteMessage.php#L62) change, correct?

**Comment by sergiitk** [comment]
Looks right.

**Comment by DFurnes** [comment]
Updated configuration on Cats Gone Good, so should be good now!

**Comment by sergiitk** [comment]
Confirming that
![screen shot 2015-06-24 at 12 32 53 am](https://cloud.githubusercontent.com/assets/672669/8317780/96905a34-1a08-11e5-8444-c10aa3bd19d8.png)

**Comment by mshmsh5000** [comment]
Verrr verrr nice. I confirmed as well.
