### ISSUE TITLE
Merge vars need tested 

### ISSUE THREAD

**Issue by marahml** [DoSomething/voting-app#382]
Merge vars for AGG transactional (sign up and global weekly do) emails have not been tested. Old template did not have correct merge vars in it.

Merge tags: 
- Candidate (athlete) name 
- Candidate (athlete) link
- User first name

**Comment by sergiitk** [comment]
'GET STARTED' button link is wrong. Now it's set to https://www.dosomething.org/campaigns/mirror-messages

**Comment by DFurnes** [comment]
I think that @ArielSD verified that these are all being sent correctly, but let's double-check before closing the issue.

**Comment by deezone** [comment]
@ArielSD I've added all of the available marge vars tags available in both the vote and weekly do transactional email templates. Please confirm they're working.

**Comment by DFurnes** [comment]
@ArielSD Is this safe to close?

**Comment by DFurnes** [comment]
I've been given the go-ahead. Closing! :hammer:
