### ISSUE TITLE
"View this in your email in your browser" not hyperlinked in vote transactional email

### ISSUE THREAD

**Issue by namimody** [DoSomething/voting-app#386]
Cannot click "view this email in your browser"

![image](https://cloud.githubusercontent.com/assets/12396076/8364748/841fab62-1b56-11e5-9fdd-3cd836fb305c.png)

**Comment by deezone** [comment]
@namimody This functionality is not available. The text and link should be removed from the template. @ArielSD can take care of it.

**Comment by DFurnes** [comment]
Verified fixed by @ArielSD. Closing! :hammer:
