### ISSUE TITLE
“No input file specified." after deploys

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#405]
Fastly is caching the extremely unhelpful `"No input file specified."` response after each deploy, until we clear cache.

**Comment by DFurnes** [comment]
Via @mshmsh5000 in chat:

> Usually means that there’s an order-of-operations problem in the deploy itself.
> 
> One way to analyze is to deploy to an internal URL that’s guaranteed not to get public traffic. Then you can see exactly what state the app is in after deploy, and what changes on its first request.

**Comment by mshmsh5000** [comment]
https://blog.martinfjordvald.com/2011/01/no-input-file-specified-with-php-and-nginx/

**Comment by DFurnes** [comment]
Going to close this in favor of DoSomething/devops#82 since it seems to have been forgotten.
