### ISSUE TITLE
Tapping an athlete causes "a problem"

### ISSUE THREAD

**Issue by cjcodes** [DoSomething/voting-app#408]
Steps to reproduce:
- Visit page (anonymously) in mobile safari (both via Facebook app and via Safari app)
- Tap an athlete
- Poof!

Screenshot of the error:
![img_0854](https://cloud.githubusercontent.com/assets/805867/8464015/36db3d24-200d-11e5-82fb-1ece7fa81d44.PNG)

**Comment by DFurnes** [comment]
This has been mitigated by #410, since we're no longer exploding poor mobile devices with bajillions of candidates on load. Closing!
