### ISSUE TITLE
Swap out email for phone

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#434]
When fastly code is one of the following, we will want to collect phone numbers instead of email addresses. 
- [ ] mx
- [ ] br

for all other global users we will continue to collect email addresses

**Related**:
- https://github.com/DoSomething/voting-app/issues/439

**Comment by DFurnes** [comment]
Going to close this issue, since we're using a new ruleset in #439 (collecting email for _all_ users, and SMS is only optional in countries where we have an SMS presence).
