### ISSUE TITLE
Transactional Payload Update

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#437]
What are the values currently being sent in the Message Broker transaction request? The values will need to be updated to support changes in the Message Broker system for changes in email and SMS.

Changes / updates / additions to the "first vote" transactional request payload:

**Updated US Values Example**:

```
  "application_id" => "CGG"
  "user_language" => "en" (based on logic in Drupal app)
  "user_country" => "US"
  "email_template" => "mb-votingapp-vote-US"
  "mobile_opt_in_path_id" => "170071"
  "mailchimp_list_id" => "f2fab1dfd4"
```

**Notes**:
- [x] `user_language" => "en"` : Based on logic in Drupal app -> https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.module#L433-L450. See Issue https://github.com/DoSomething/voting-app/issues/282 for collection of broswer language. Could default to `en` considering the CGG app is only English.
- [x] `email_template` : value has `user_country` appended to the end. 
- [x] `opt_in_path_id`, Mobile Commons ID (170071) for US users, mGage / Communicate Pro ID (TBD) for global users
- [x] `mailchimp_list_id`, : `f2fab1dfd4` "US users" / `66fd18c5a9.` "BR users" / `4f8e24d4f5` "MX users", `8e7844f6dd` "Global users"
- [x] remove `mailchimp_grouping_id` and `mailchimp_group_name`.

**Current Payload Example**:

```
(
    [first_name] => Test Dee
    [birthdate_timestamp] => 929232000
    [country_code] => US
    [candidate_id] => 2
    [candidate_name] => Brigitte Kuphal
    [mobile] => 3479886705
    [mobile_tags] => Array
        (
            [0] => agg
            [1] => 2
            [2] => GENDER_X
        )

    [application_id] => AGG
    [mc_opt_in_path_id] => 180170
    [mailchimp_grouping_id] => 10677
    [mailchimp_group_name] => AGG2015
    [mailchimp_list_id] => f2fab1dfd4
    [activity] => vote
    [activity_timestamp] => 1447199936
)
```

**Related**:
- mGage SMS support for MX and BR: https://github.com/DoSomething/mbc-registration-mobile/issues/19
- `user_language` : https://github.com/DoSomething/voting-app/issues/282

**Comment by DFurnes** [comment]
Hey @DeeZone! Here's the [current payload](https://github.com/DoSomething/voting-app/blob/b4342bcc29d2c2bf099a5db6bbcb40c81769d030/app/Handlers/Events/SendFirstVoteMessage.php#L30-L64) we're sending. Right now we're varying the payload based on whether or not a user is US... I'll be putting up a PR soon to vary that based on whether it's in our array of "cellular" countries (so the domestic payload will apply to `US`, `BR`, and `MX`).

**Comment by DeeZone** [comment]
Changes / updates / additions to the "first vote" transactional request payload:

**US Values Example**:
```
  "application_id" => "CGG"
  "user_language" => "en" (based on logic in Drupal app)
  "user_country" => "US"
  "email_template" => "mb-votingapp-vote-US"
  "opt_in_path_id" => "170071"
  "mailchimp_list_id" => "f2fab1dfd4"
```
**Notes**:
- `user_language" => "en"` : Based on logic in Drupal app -> https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_global/dosomething_global.module#L433-L450
- `email_template` : value has `user_country` appended to the end. 
- `opt_in_path_id`, Mobile Commons ID (170071) for US users, mGage / Communicate Pro ID (TBD) for global users
- `mailchimp_list_id`, : `f2fab1dfd4` "US users" / `66fd18c5a9.` "BR users" / `4f8e24d4f5` "MX users", `8e7844f6dd` "Global users"

**Comment by deezone** [comment]
@DFurnes Updated issue description with details for your review.

**Comment by DFurnes** [comment]
> Could default to en considering the CGG app is only English.

Agreed, we aren't translating the UI for Celebs Gone Good like we do in Phoenix, so it probably makes sense to still send all messaging in English to keep the experience consistent.

**Comment by DFurnes** [comment]
Updated payload seems good to me! Will let you know once the app is sending those along.

**Comment by DFurnes** [comment]
@DeeZone Should `user_country` be the normalized user country (e.g. `US`, `BR`, `MX`, or `global`) or the actual country code stored on that user object?

**Comment by DFurnes** [comment]
@DeeZone Another Q! Should the opt-in path ID key be `mobile_opt_in_path_id` or `opt_in_path_id`? I see both in the examples. :grin:

**Comment by deezone** [comment]
@DFurnes 

> Should `user_country` be the normalized user country (e.g. `US`, `BR`, `MX`, or `global`) or the actual country code stored on that user object?
- The `user_country` can be the actual country code, no need for the value to be normalized.

> Should the opt-in path ID key be mobile_opt_in_path_id or opt_in_path_id? I see both in the examples.
- Opps, should be `mobile_opt_in_path_id`.

**Comment by DFurnes** [comment]
Thanks! Updated the PR.

**Comment by DFurnes** [comment]
Done, and deployed to both [Cats Gone Good](https://www.catsgonegood.com) and [Celebs Gone Good](https://www.celebsgonegood.com) (although CGG is "closed" so not ideal for testing). Both share the same environment variables so should be identical for testing purposes.
