### ISSUE TITLE
SMS + Email rules for CGG 2015

### ISSUE THREAD

**Issue by joolaay** [DoSomething/voting-app#439]
If US, then Email required / SMS optional

If MX/BR, then Email required / SMS optional

If neither, then Email only

**Related**:
- See https://github.com/DoSomething/voting-app/issues/437 for guidlines / examples of the `payload` structure to support Email and SMS.
- https://github.com/DoSomething/voting-app/issues/434

---

cc @marahml @DFurnes @mnelson338

**Comment by DFurnes** [comment]
Fab! :+1:

**Comment by joolaay** [comment]
cc @DeeZone

**Comment by DFurnes** [comment]
This should be good to go on the application side of things.
