### ISSUE TITLE
CGG BZ/MX users, save custom information to SMS Service profiles

### ISSUE THREAD

**Issue by classicfreddie** [DoSomething/voting-app#442]
Save first vote values for `CGG2015` to user (by mobile number) profiles. This includes both US (Mobile Commons) and global affiliates MX and BR (mGage).

**Comment by deezone** [comment]
As defined in https://github.com/DoSomething/voting-app/blob/b4342bcc29d2c2bf099a5db6bbcb40c81769d030/app/Handlers/Events/SendFirstVoteMessage.php#L41-L44.

The current tags being sent to both Mobile Commons and mGage are:

```
            $payload['mobile_tags'] = [
                env('APP_NAME_TAG', 'votingapp'),
                $event->candidate->id,
                'GENDER_'.$event->candidate->gender,
            ];
```

Do this values still make sense?
- `candidate->id`
- `candidate->gender`.
  I suspect `candidate->gender` comes from AGG. Is this of value for CGG?

**Comment by deezone** [comment]
Duplicate: https://github.com/DoSomething/voting-app/issues/441

**Comment by classicfreddie** [comment]
For CGG we only need the candidate->id (assuming that's the name of the celebrity they are voting for). No need for gender, that was only for AGG.

**Comment by marahml** [comment]
@classicfreddie are you good to set up this message in the UI side in mGage? cc @DeeZone

**Comment by deezone** [comment]
@classicfreddie Lets schedule some time together to walk through Communicate Pro (mGage). I'm happy to share my limited experience and discover together. My goal is to end up with the mGage `opt_in` IDs for BR and MX welcome signups for the Drupal app and "Thanks for voting" in MX and BR for CGG.

cc @marahml

**Comment by classicfreddie** [comment]
Hey @DeeZone - what is the name of the custom field that the user's vote is being saved to?

**Comment by classicfreddie** [comment]
@DeeZone Created the custom field: titled - CGG2015_1st_vote

**Comment by deezone** [comment]
@classicfreddie thanks, confirmed it works in Mobile Commons (US votes). I'll leave it to you to close this issue once you do your own testing when I release this feature to production.

**Comment by deezone** [comment]
@classicfreddie Can we close this issue?
