### ISSUE TITLE
Error connecting to message broker

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#452]
[Cats Gone Good](http://www.catsgonegood.com) is having trouble connecting to Message Broker. When trying to create the queue connection after a user votes, it instead blows up with the following error:

```
'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error Connecting to server (110): Connection timed out'`
```

Boo. I double-checked the connection settings ([example values](https://github.com/DoSomething/voting-app/blob/13f221dbba5278b3dca39a70d4cc57e0d8a338ec/.env.example#L19-L23)) were set correctly and everything seemed okay for the most part. We were using a static IP rather than a named host, though, so I tried switching the IP address to the provided `mq0` hostname. Now getting the following error:

```
Error Connecting to server (0): php_network_getaddresses: getaddrinfo failed: Name or service not known
```

And that's the current state of affairs! Haaaaaalp! :fearful:

**Comment by DFurnes** [comment]
@sheyd Would you mind helping troubleshoot? This is a blocker for @DeeZone to be able to test message broker functionality so it'd be good to get worked out soonish.

**Comment by sheyd** [comment]
Yeah, give me a minute.

**Comment by sheyd** [comment]
Fixed!
