### ISSUE TITLE
GB users to wrong mailchimp_list_id

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#457]
User from the `user_country` "GB" should be assigned to the "UK" `mailchimp_list_id` -> `fd4...`.

**Comment by DFurnes** [comment]
Hey @DeeZone, can you send me the full list ID that should be sent for GB users? I can only find list IDs for `US`, `MX`, `BR`, and `global` when looking back at previous issues.

**Comment by deezone** [comment]
Sent VInspired / GB MailChimp list ID via Slick #voting-app
