### ISSUE TITLE
Customizable category sorting

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#467]
Currently categories are sorted alphabetically (since that's how we wanted things displayed for Athletes Gone Good). Since we have less categories for Celebs Gone Good, we're hoping to sort them differently.

We need to think about adding a custom (e.g. user-defined) sort ranking for categories.

**Comment by DFurnes** [comment]
One low-effort fix for this could be sorting by `id`, but that's problematic if we don't enter them in the "right order" off the bat (and why we decided to sort alphabetically on AGG instead of by `id`).

**Comment by DFurnes** [comment]
And we settled on an easy fix! Closing! :hammer:

**Comment by angaither** [comment]
~for the future~ we are changing the names of the categories.
