### ISSUE TITLE
CGG Mexico and Brazil, save users phone number to lists 

### ISSUE THREAD

**Issue by classicfreddie** [DoSomething/voting-app#468]
Brazil: 
-List name: Brazil_CelebsGoneGood_2015
-URL: https://communicatepro.mgage.com/consoleapp/viewOptinList.jspx?id=464234

Mexico: 
-List name: Mexico_CelebsGoneGood_2015
-URL: https://communicatepro.mgage.com/consoleapp/viewOptinList.jspx?id=464232

**Comment by classicfreddie** [comment]
@DeeZone I've created the 2 way programs to opt Mexican and Brazilian users into. Can we do a test again with the US short code?  

Mexico: 
URL: https://communicatepro.mgage.com/consoleapp/view2Way.jspx?id=90906
ID: 90906
Keyword: MXCGG

Brazil: https://communicatepro.mgage.com/consoleapp/view2Way.jspx?id=90938
URL:  90938
Keyword: BZCGG

**Comment by classicfreddie** [comment]
@DeeZone since we can't test the messaging for MX/BZ, let's test with the US short code to make sure we have it set up correctly. 

US: https://communicatepro.mgage.com/consoleapp/view2Way.jspx?id=90862
ID: 90862
Keyword: FREDFRI

You can use my number - 7024390195 to test if you'd like

**Comment by deezone** [comment]
Test sent, please confirm:

```
    // https://communicatepro.mgage.com/consoleapp/viewTemplateProgram.jspx?id=115658
    $gatewayID = '115658';
    // Friday 2 Shortcode
    $optInListID = '66978';
     // US Test
    $optInKeyword = 'FREDFRI';
     // Freddie
    $mobileNumber = '17024390195';
```

**Comment by classicfreddie** [comment]
@DeeZone I received the message, but received it 4 times. Not sure if you tested multiple times?

**Comment by deezone** [comment]
@classicfreddie Perfect! That was me testing... 4 is the number I wanted to hear :) I'll point everything to the actual MX and BR lists to wrap this issue up.

**Comment by classicfreddie** [comment]
@DeeZone amazing! We'll sync again in our messaging meeting today. Micah is connecting me with someone on the ground in BZ/MX so we can test out that they receive the messages too! I'll get you those numbers ASAP

**Comment by deezone** [comment]
@classicfreddie I found a service that allows receiving international SMS messages online in various countries including Brazil: http://receivefreesms.com.

I've run some tests with their numbers. Brazil looks like it's working.

**Comment by classicfreddie** [comment]
@DeeZone still waiting on a Mexican number, but I think it's okay for us to close this for now. Thanks!
