### ISSUE TITLE
CGG US SMS, not receiving transactional message

### ISSUE THREAD

**Issue by classicfreddie** [DoSomething/voting-app#469]
I tested with the phone number 702-439-0195, but I'm not receiving messaging or being added into the Mobile Commons opt in path.

Opt In Path ID: 196577 

cc: @DeeZone

**Comment by DFurnes** [comment]
I just tested this with some dummy information on Cats Gone Good and dumped the payload being sent to Message Broker:

<img width="575" alt="screen shot 2015-11-23 at 5 32 19 pm" src="https://cloud.githubusercontent.com/assets/583202/11352070/2fc209e2-9208-11e5-817d-94ab4d036bb8.png">

@DeeZone I think everything looks like it's being prepared okay on my end, but let me know if you see any problems! Happy to sit down and help debug if there's any way I can help as well.
