### ISSUE TITLE
CGG Form Copy: Brazil

### ISSUE THREAD

**Issue by marahml** [DoSomething/voting-app#470]
Add copy to the CGG form for Brazilian users to explain that we will not be texting them yet.

Options: 
- As soon as it's available, we'll let you know when you can text in your volunteer actions!
- We're working on being able to text members in your country!
- In the future, we'll be able to text you cool things like this!

![screen shot 2015-11-24 at 12 43 18 pm](https://cloud.githubusercontent.com/assets/6784628/11375421/5734b712-92a9-11e5-8844-846869c5abd9.png)

**Comment by DFurnes** [comment]
@marahml Are you thinking this text would be added to the "fine print" below? Or as a separate "fine print" below the cell field? Or normal paragraph text?
