### ISSUE TITLE
Invalid user_country for non US votes

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#471]
The `user_country` is not being set correctly when a user votes from outside of the US. When using TorGuard, a setting of Mexico, Brazil and Egypt all produce `user_country => 'US'` in the vote transactional request. The following tools are used to confirm user location before submitting a vote:
- https://ipcim.com/en/?p=where (lists user location based on IP)
- dosomething.org (content changes on landing page)
- google.com (page title image changes based on user country)

Example payload sent to Message Broker for a user vote from Egypt. Note: `[user_country] => US` and `[email_template] => mb-cgg2015-vote-US`. This results in:
- the wrong SMS service being used
- the wrong email template being used in the transactional email
- the email address be added to the wrong MailChimp account/list (`mailchimp_list_id`)

```
Array
(
    [first_name] => Ariel
    [birthdate_timestamp] => 574473600
    [user_country] => US
    [candidate_id] => 430
    [candidate_name] => Ariel Winter
    [merge_vars] => Array
        (
            [FNAME] => Ariel
            [CANDIDATE_NAME] => Ariel Winter
            [CANDIDATE_LINK] => http://www.catsgonegood.com/candidates/ariel-winter
            [GENDER] => F
        )
    [user_language] => en
    [email] => ascottdicker+Test@dosomething.org
    [subscribed] => 1
    [email_template] => mb-cgg2015-vote-US
    [email_tags] => Array
        (
            [0] => votingapp
            [1] => 430
            [2] => GENDER_F
        )
    [mailchimp_list_id] => f2fab1dfd4
    [application_id] => CGG
    [activity] => vote
    [activity_timestamp] => 1448389454
)
```

**Comment by DFurnes** [comment]
Just tested this using TorGuard from Mexico and I'm seeing the correct payload:

<img width="575" alt="screen shot 2015-11-24 at 1 49 06 pm" src="https://cloud.githubusercontent.com/assets/583202/11377131/5c88b26e-92b2-11e5-8d1f-3a698ca19c3b.png">

And from Brazil:

<img width="580" alt="screen shot 2015-11-24 at 1 54 23 pm" src="https://cloud.githubusercontent.com/assets/583202/11377250/e7a25b66-92b2-11e5-9482-7c6755bbcc4a.png">

Are you sure you are clearing your session between visits? If you start a session in one country, it will cache the country code for the remainder of the session (i.e. until hitting `/logout`).

**Comment by DFurnes** [comment]
The cached country code was added in #342 so that we could use `?country_code=` to test country codes without using a proxy. If we're not using that functionality, perhaps we should remove it so it makes this kind of testing easier.

**Comment by deezone** [comment]
:boom: the old `?country_code=`... good to know!

Trying another round of testing.

**Comment by deezone** [comment]
Provided the FASTLY headers do their job it looks like we're good. Thanks for pointing out the `?country_code=` functionality, very helpful.
