### ISSUE TITLE
BR number format suggestion invalid

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#472]
The suggested number format in the vote submission form for Brazil does not validate.

![image](https://cloud.githubusercontent.com/assets/2119264/11380117/3a442494-92c2-11e5-8d48-166fedb7f978.png)

but a submisison following the suggested phone number format produces a form submission error.

![image](https://cloud.githubusercontent.com/assets/2119264/11380060/db1f09c0-92c1-11e5-845c-7969865743ef.png)

**Suggested Format**:
- https://en.wikipedia.org/wiki/Telephone_numbers_in_Brazil
- Typical format:
  - AA NNNN-NNNN
  - AA 9NNNN-NNNN

**Comment by DFurnes** [comment]
I found this super nice [Laravel phone number validation](https://github.com/Propaganistas/Laravel-Phone) package, based on Google's `libphonenumber`. From some testing on my local machine, it works great for US numbers and 10-digit BR numbers, but not 11-digit BR numbers.

Still trying to figure out what's up with that, but another potential quick fix could just be updating our regex to be less strict (and then perhaps updating to better validation post-launch).

**Comment by DFurnes** [comment]
One really cool thing about the package mentioned above is that it can validate a number by country code, so we could prevent people from entering a BR phone number in the US (and vice versa). The flip side is that in some cases that _might_ disallow numbers that carriers would consider local. From [a docblock in libphonenumber](https://github.com/giggsey/libphonenumber-for-php/blob/d0bfaec05d1881f56bbb00e6e4c7004b49562eb9/src/libphonenumber/PhoneNumberUtil.php#L2621-L2624):

> For example, this method will mark numbers from British Crown dependencies such as the Isle of Man as invalid for the region "GB" (United Kingdom), since it has its own region code, "IM", which may be undesirable.

Not a deal breaker, but we should make sure there aren't any cases like this for `MX` or `BR`! 

/cc @DeeZone @classicfreddie

**Comment by DFurnes** [comment]
Just for future reference, there's some further discussion on this happening in #477! :page_with_curl:
