### ISSUE TITLE
CGG2015: Stripped Formatting In Transactionals

### ISSUE THREAD

**Issue by ArielSD** [DoSomething/voting-app#473]
The voting confirmation transactional template for CGG2015 is losing the formatting it has in MailChimp when it gets to my inbox as a user. This is for all cases, US, Global, Brazil, and Mexico. I'm using Gmail. 

The first line "Thanks for voting..." is supposed to be H2, but looks small. The second section, from "Good news:...December 30" is supposed to be H3, but looks small. The rest of the text should be 16px font and #606060 in color, except the "More good news..." and "Want to make an impact?" lines should be bolded. 

Also, the links should be bolded, in DoSomething blue (#23b7fb), and not underlined. Two screenshots below: The first is an example of proper formatting, the second is the incorrect CGG template. 

Links to templates in MailChimp:

U.S.: https://us4.admin.mailchimp.com/templates/editor?id=56617
Global: https://us4.admin.mailchimp.com/templates/editor?id=56761
Brazil: https://us4.admin.mailchimp.com/templates/editor?id=56769
Mexico: https://us4.admin.mailchimp.com/templates/editor?id=56765

Issues by priority:
- [ ] Link formatting
- [ ] Proper text size
- [ ] Proper text color

![screen shot 2015-11-24 at 5 26 14 pm](https://cloud.githubusercontent.com/assets/8696853/11382698/503f7b68-92d1-11e5-9531-e0d525eaf2cd.png)

![screen shot 2015-11-24 at 4 57 26 pm](https://cloud.githubusercontent.com/assets/8696853/11381938/134db28c-92cd-11e5-9a5b-ec40e8e1235f.png)

**Comment by DFurnes** [comment]
Hey @ArielSD! I'm not involved in transactional emails, so I'm not sure where best to start troubleshooting that. I'd recommend checking with @DeeZone or whoever is typically responsible for them.

**Comment by deezone** [comment]
@ArielSD Perhaps @weerd or @sbsmith86 would be the right ones to take a look at this issue?

**Comment by ArielSD** [comment]
Thanks, @DFurnes and @DeeZone !

@sbsmith86 or @weerd Would either of you have time for this before the December 1st launch? It's not a launch blocker, but definitely looks sloppy as it is. Thanks!

CC: @marahml

**Comment by deezone** [comment]
@ArielSD Perhaps a list of issues by priority based on the screenshot that needs addressing?

**Comment by ArielSD** [comment]
@DeeZone Updated!

**Comment by deezone** [comment]
@ArielSD Added checkboxes :)
