### ISSUE TITLE
Frozen page when viewing celebrity

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/voting-app#478]
Steps to reproduce:
- went to www.celebsgonegood.com
- scrolled down to Aziz Ansari
- Clicked on Vote button
- Stuck on the following screen

![image](https://cloud.githubusercontent.com/assets/6330971/11505050/62e42c38-9816-11e5-9bad-a457db9fd584.png)

**Comment by mikefantini** [comment]
Also this is the url I get when I click on Vote http://www.celebsgonegood.com/?query=

**Comment by DFurnes** [comment]
Just tested in Safari 9 and Chrome 46, and not able to reproduce. Does this happen reliably for you?

**Comment by angaither** [comment]
same, unable to reproduce this. @mikefantini you are a gifted bugsman

**Comment by mikefantini** [comment]
Hmm yeah I just tested a few more times and I'm unable to reproduce. Not sure exactly what happened...

I thought it was maybe that I clicked vote immediately after scrolling which tripped it up, but I haven't been able to create the issue again.

May be worth keeping an eye on? Your call whether to keep this open or not.

**Comment by DFurnes** [comment]
Going to close for the moment, but will re-open if we get any more reports.
