### ISSUE TITLE
First time a user votes they receive a whoops error

### ISSUE THREAD

**Issue by mikefantini** [DoSomething/voting-app#479]
Steps to recreate:
- Go to www.celebsgonegood.com
- Scroll down to Michael B. Jordan
- Click vote
- Enter information
- Submit
- Get taken to https://www.celebsgonegood.com/votes with the following error message:

![image](https://cloud.githubusercontent.com/assets/6330971/11505113/c0bf1fc0-9816-11e5-8ef7-38606cb55582.png)

I saw Adam have this issue as well.

**Comment by DFurnes** [comment]
There's some discussion on this in the #voting-app Slack channel. The error in question:

```
[2015-12-01 15:01:41] production.ERROR: exception 'PhpAmqpLib\Exception\AMQPRuntimeException' with message 'Error Connecting to server (111): Connection refused' in /var/www/voting-app/releases/20151120191855/vendor/videlalvaro/php-amqplib/PhpAmqpLib/Wire/IO/StreamIO.php:106
```

We saw a similar issue on Cats Gone Good a ways back, and @sheyd was able to fix it with some DevOps black magic. :crystal_ball:

**Comment by DFurnes** [comment]
And this is fixed! @sheyd figured out that the `mq0` host for Message Broker wasn't in the `etc/hosts` file so the connection wasn't going anywhere. Closing. :hammer:
