### ISSUE TITLE
no cell field on mobile

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#480]
![image](https://cloud.githubusercontent.com/assets/645205/11505276/9def78ea-9817-11e5-8fad-6d84baa63318.png)

**Comment by DFurnes** [comment]
Hmm, I'm getting the proper fields when loading the page over Verizon LTE. I wonder if AT&T isn't getting the right location headers from Fastly? Let's test with other phones later today.

**Comment by angaither** [comment]
Related, duplicate of #482

**Comment by DFurnes** [comment]
Closing since this should be fixed whenever we get a solution to #482.
