### ISSUE TITLE
Northstar connection having issues

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#487]
We're getting errors when trying to forward user's interests (e.g. candidate category) to Northstar:

```
[2015-12-02 18:10:14] production.DEBUG: Northstar API Exception {
  "code":405,
  "message":"Client error response [url] https://northstar.dosomething.org/v1/users/565f3431469c64a8178b92ea [status code] 405 [reason phrase] Method Not Allowed",
  "body": {
    "error":{ "code":405, "message":"" }
  }
} 
```

I believe this is due to breaking changes made to the endpoint in DoSomething/northstar#214.

**Comment by DFurnes** [comment]
We can fix this by updating Jubilee to use the [Northstar-PHP](https://github.com/DoSomething/northstar-php) library.

**Comment by katiecrane** [comment]
@DFurnes how do I reproduce this error? aka how do I make sure it's fixed 😁

**Comment by DFurnes** [comment]
It actually shouldn't be an issue anymore, since we made some fixes to this on the Northstar end. But it'd be nice to use the PHP library here rather than having another implementation of all those API calls.
