### ISSUE TITLE
mailchimp_list_id value invalid - full array of keys

### ISSUE THREAD

**Issue by deezone** [DoSomething/voting-app#494]
In some cases, when a `user_country` => `US` vote transaction is submitted the entire MailChimp list ID array is submitted as the `mailchimp_list_id` value rather than a specific ID value. The invalid `email_template` value of `mb-cgg2015-vote-` suggests the missing header value from FASTLY is the root of the issue.

I can trap this issue on the Message Broker side or the voting app can ensure the `mailchimp_list_id` is a string?

**Example**:

```
Array
(
    [activity] => vote
    [activity_timestamp] => 1449534317
    [email] => xxx@xxx.com
    [email_template] => mb-cgg2015-vote-
    [mailchimp_list_id] => Array
        (
            [US] => f2fab1dfd4
            [GB] => fd48935715
            [BR] => 66fd18c5a9
            [MX] => 4f8e24d4f5
            [global] => 8e7844f6dd
        )

    [application_id] => CGG
    [source] => CGG
    [fname] => Estefania
    [merge_vars] => Array
        (
            [FNAME] => Estefania
            [CANDIDATE_NAME] => Fifth Harmony
            [CANDIDATE_LINK] => https://celebsgonegood.com/candidates/fifth-harmony
            [MEMBER_COUNT] => 4.6 million
        )

    [email_tags] => Array
        (
            [0] => votingapp
            [1] => 65
            [2] => GENDER_F
        )

    [user_country] => US
    [user_language] => en
    [birthdate_timestamp] => 922752000
    [candidate_id] => 65
    [candidate_name] => Fifth Harmony
)
```

**Comment by DFurnes** [comment]
Well, that is very strange. This only happens when `user_country` is `US`? And if so, not consistently for all of those requests? :confused:

**Comment by DFurnes** [comment]
All instances of the country code used in that payload should all be coming from the same serialized `country_code` value passed to the event handler... so it's _super_ weird that it's showing `US` in one case and an empty string elsewhere in the same payload.

**Comment by deezone** [comment]
I can provide additional "real case" examples for specific email addresses if you like? It seems to be happening every few minutes depending on the rate of voting.

**Comment by DFurnes** [comment]
Ah, that's tricky. If the given key is null, then `array_get($array, $key, $fallback)` returns the whole array. Blahhhh.

**Comment by deezone** [comment]
@DFurnes 

Still seeing payloads from the Voting App with full array lists for `mailchimp_list_id` and invalid `email_template` values. 

`[user_country] => US` was set by mbc-externalApplications-services (https://github.com/DoSomething/mbc-externalApplications-services/blob/master/src/MBC_ExternalApplications_Events_Consumer.php#L187) when a NULL value for `user_country` was encountered. 

I suspect this user was from Germany:

```
(
    [activity] => vote
    [activity_timestamp] => 1450124158
    [email] => xyz.xyz@gmx.de
    [email_template] => mb-cgg2015-vote-
    [mailchimp_list_id] => Array
        (
            [US] => f2fab1dfd4
            [GB] => fd48935715
            [BR] => 66fd18c5a9
            [MX] => 4f8e24d4f5
            [global] => 8e7844f6dd
        )

    [application_id] => CGG
    [source] => CGG
    [fname] => xxx
    [merge_vars] => Array
        (
            [FNAME] => xxx
            [CANDIDATE_NAME] => Anna Kendrick
            [CANDIDATE_LINK] => https://celebsgonegood.com/candidates/anna-kendrick
            [MEMBER_COUNT] => 4.6 million
        )

    [email_tags] => Array
        (
            [0] => votingapp
            [1] => 18
            [2] => GENDER_F
        )

    [user_country] => US
    [user_language] => en
    [birthdate_timestamp] => 904780800
    [candidate_id] => 18
    [candidate_name] => Anna Kendrick
)
```
- `[activity_timestamp] => 1450124158`:
  GMT: Mon, 14 Dec 2015 20:15:58 GMT

**Comment by DFurnes** [comment]
@DeeZone This fix hasn't been deployed yet, since we usually don't deploy on Fridays. You can see what has and hasn't been deployed to different environments on the [builds history](https://app.wercker.com/#applications/5463a6bde3d1713625001c35/tab/builds) on Wercker (note you have to be logged in for deploy badges to appear).

I'll deploy tomorrow morning when I'm in the office.

**Comment by deezone** [comment]
@DFurnes Thanks for the pointers... this leaves me wanting to add some Wercker love to my projects. I hope to poke you soon to get some suggestions / details from you. Until then, I'll keep an eye on the votingApp deployments.
