### ISSUE TITLE
Add ability to remove "write in" text at the bottom of the page.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#505]
We want to be able to toggle off the "Was there a candidate we missed?" blurb at the bottom of the page for this campaign. It might make sense to refactor this section to be a Markdown text area (rather than hard-coded copy), and then conditionally display it only if the text area is not empty.

**Comment by namimody** [comment]
@katiecrane this functionality works! however, what's the logic behind the writein_link field here: 
![image](https://cloud.githubusercontent.com/assets/12396076/14532521/49bdf7c4-022f-11e6-8675-808b2122b776.png)

should the copy in the markdown field hyperlink to the link listed?

**Comment by katiecrane** [comment]
Ahhhh @namimody the writein_link is leftover from how the write in text used to work. It was less customizable and that is one of the fields that was pulled in. I'm pretty sure it can be removed.

cc: @DFurnes

**Comment by DFurnes** [comment]
@katiecrane :+1: :fire:
