### ISSUE TITLE
Message Broker template should only use "whitelisted" countries

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#525]
We currently send _any_ country code that's provided by Fastly when indicating a template to be used for transactional messaging in Message Broker, and [only use the `XG` fallback if country code is not available](https://github.com/DoSomething/voting-app/blob/890151a27fa4b729ee8bb378ef7df8df07328a57/app/Listeners/SendFirstVoteMessage.php#L70).

This year, the consumers will not be handling fallbacks for unsupported country code templates so we'll add some code to normalize this value to a set of supported templates again.

**Comment by deezone** [comment]
To be clear, the consumers do have fallback code for unsupported countries. The logic is to use the country code when `US` or any of our affiliates countries is making the transaction.

It gets fuzzy when the country code is an actual affiliate but the business logic is that only `US` and `XG` (all other global countries) will get messages. I suggest this issue support the "special" business logic of specifying the `XG` template when countries like `MX` and `BZ` are triggering the transaction.

**For reference**, the current mbc-transactional-email consumer logic:
- https://github.com/DoSomething/mbc-transactional-email/blob/master/src/MBC_TransactionalEmail_Consumer.php#L345-L359
