### ISSUE TITLE
Update to latest Gateway release.

### ISSUE THREAD

**Issue by DFurnes** [DoSomething/voting-app#536]
The latest [Gateway](https://github.com/DoSomething/gateway) release has all sorts of goodies: OAuth support for API clients, OpenID Connect sign-up, and all sorts of fun new toys. 🐻

We should use it here.

**Comment by DFurnes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) As an admin, I want CGG authenticated via northstar oAuth](https://trello.com/c/wsq4WeIw/78-5-as-an-admin-i-want-cgg-authenticated-via-northstar-oauth)

**Comment by DFurnes** [comment]
This was done in #537.

**Comment by itsjoekent** [comment]
Weird, must have forgot to attach the issue
