### ISSUE TITLE
Admin form to create admin users

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#79]

**Comment by DFurnes** [comment]
We currently have an [Artisan command](https://github.com/DoSomething/voting-app/blob/9bc94614f3751f30d90e5126fe0757a4ed59a98b/app/Console/Commands/CreateAdminUser.php) for this, but it could make sense to expose in the admin UI as well. Another potential route would be to  query a user's privileges from Northstar.

**Comment by angaither** [comment]
right, but we don't have roles/permissions in northstar
since ideally each app would be in charge of a users' permissions within the app

this one is just a nice to have

**Comment by DFurnes** [comment]
I feel like there's value in having a centralized source for authorization/role information (e.g. is a user a DS employee, or what team they're on). But yep, doesn't exist now and probably won't anytime soon.

**Comment by DFurnes** [comment]
And this is something we're actually doing now! 🐎 🚀 👏 💥 Closing.
