### ISSUE TITLE
Message broker testing

### ISSUE THREAD

**Issue by angaither** [DoSomething/voting-app#94]
Is it working?
- send an email to mailinator, use their api to see if the message was delivered
- is there a cell phone version of this?

**Comment by deezone** [comment]
Perhaps the Mobile Commons API? https://mobilecommons.zendesk.com/hc/en-us/articles/202052534-REST-API

Looks like `profile` (https://secure.mcommons.com/api/profile) will tell you if a number is registered and received a message.

**Comment by deezone** [comment]
@angaither MailChimp will reject email addresses from Mailinator as "fake". Mandrill will attempt to send the email message.

**Comment by DFurnes** [comment]
This makes sense to test somewhere in Message Broker (and I think coverage for this might already exist?). Going to close this issue since Voting App should be treating Message Broker as an external dependency and mocking its responses for testing purposes.
